# Generated by Django 4.2 on 2024-06-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_newslettersubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/")),
                ("caption", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
