# Generated by Django 4.2 on 2024-06-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_galleryimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="services/")),
                ("description", models.TextField()),
            ],
        ),
    ]
