# Generated by Django 4.2 on 2024-06-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="phone_number",
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
