# Generated by Django 4.2 on 2024-09-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0007_contact_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contact",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
